version: '2'
services:
  www-fs-kogni:
    container_name: www-fs-kogni
    build: .
    image: 'fsinf/kogni-website:latest'
    #restart: always
    hostname: 'www.fs-kogni.fsi.uni-tuebingen.de'
    ports:
      - '134.2.220.61:8002:80'
      - '134.2.220.61:8003:443'
