#version: '2'
version: '3.2'
services:
 jekyll:
   container_name: cyberauftritt_jekyll
   image: fsinf/cyberauftritt:latest
   #command: bash -c 'echo "0.0.0.0 www.fsi.uni-tuebingen.de" >> /etc/hosts && bundle exec jekyll serve --host=www.fsi.uni-tuebingen.de --port=8080'
   command: bundle exec jekyll build --config /etc/deployment-config.yml,_config.yml
   volumes:
     - ./cyberauftritt-git:/srv/jekyll
     - ./deployment-config.yml:/etc/deployment-config.yml:ro
 app:
    image: fsinf/nginx:latest
    command: /usr/sbin/nginx -g 'daemon off;'
    #command: bash -c 'export JEKYLL_ENV=production && bundle exec jekyll serve --host=0.0.0.0 --baseurl="https://www.fsi.uni-tuebingen.de:444"'
    container_name: cyberauftritt_nginx
    volumes:
      - ./cyberauftritt-git/_site:/srv/jekyll
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx-hp.conf:/etc/nginx/sites-enabled/nginx-hp.conf:ro
    restart: always
    ports:
      - "192.168.134.60:8080:8080"
    depends_on:
      - jekyll
